### ISSUE TITLE
Mediastoreuk

### ISSUE THREAD

**Issue by Lional8** [1Panel-dev/appstore#1016]
[]()![image](https://github.com/1Panel-dev/appstore/assets/161793936/ec6c1bf4-ce0e-496a-a564-9f29763837a7)@![image](https://github.com/1Panel-dev/appstore/assets/161793936/8f378238-beb0-4d6e-a372-2ed6a0f2ae8d)

**Comment by wanghe-fit2cloud** [comment]
如果您在使用过程中遇到什么问题，或有进一步的需求需要反馈，请提交 GitHub Issue 到 [1Panel 项目的主仓库](https://github.com/1Panel-dev/1Panel/issues)
