### ISSUE TITLE
Port conflict with 9000 (between minio and portainer-ce)

### ISSUE THREAD

**Issue by moonrailgun** [1Panel-dev/appstore#1414]
Hi, i am developer of `Tailchat`, here is a bug report which submit in tailchat's community

i notice here is a change which change custom port to fixed one. (This: https://github.com/1Panel-dev/appstore/commit/fc534a566c40e5d83902ae599a84b78f56cc1f0a#diff-899cfc6e4dbc4c394a063167ab6b08cae48e66c17a3eb8a735ec7c20bd951a16)

we assume user will not change port of minio. actually our user never change port, its a good change

but the issue is if user install `minio` and `portainer-ce` together, because those port are all try to occupy port 9000, its will self-increasing by itself to auto resolve problem.

finally, its maybe looks like here:
```
minio admin: 9000
portainer-ce: 9001
minio api: 9002
```
*(from my user)*

and then, as application, `tailchat` will try to visit `minio:9001`. of course its will not work because api port already changed to `9002`.

**Comment by moonrailgun** [comment]
Here is a screenshot from my user:
![fa7054f96c402b5677d595ebd1519e1](https://github.com/1Panel-dev/appstore/assets/6964737/fbbba72f-92df-4e79-9f44-728b3de3ade7)
![da91806d932b3026097d0f448435293](https://github.com/1Panel-dev/appstore/assets/6964737/f8884bec-d6c3-4cb1-a55a-9b9984065c9f)

**Comment by wanghe-fit2cloud** [comment]
上述 commit 中涉及到 9001 端口是容器内部端口，与对外暴露端口无关。

**Comment by moonrailgun** [comment]
事实上这就是一个对外暴露的端口。对外暴露端口被占用，如果修改自定义端口后，下游应用无法自定义

可以查看minio的声明:

https://github.com/1Panel-dev/appstore/blob/374300776aaec7cd5a010d5f1689bc5af0ed7f77/apps/minio/2024-04-06/docker-compose.yml#L6

https://github.com/1Panel-dev/appstore/blob/374300776aaec7cd5a010d5f1689bc5af0ed7f77/apps/minio/2024-04-06/data.yml#L26-L32

**Comment by wanghe-fit2cloud** [comment]
`${PANEL_APP_PORT_HTTP}` 这个参数接收用户设置的对外暴露端口。
