### ISSUE TITLE
我推荐一下哈dify项目

### ISSUE THREAD

**Issue by stone100010** [1Panel-dev/appstore#1486]
名称：dify
介绍：Dify是一个开源的LLM应用程序开发平台。其直观的界面结合了AI工作流程、RAG管道、代理功能、模型管理、可观察性功能等，让您快速从原型到生产。
GitHub：https://github.com/langgenius/dify

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持 我们目前在 1Panel 应用商店的 `AI / 大模型` 分类中上架了 [MaxKB](https://github.com/1Panel-dev/MaxKB)，看是否能满足要求。
