### ISSUE TITLE
[FEATURE] App上架流程的可测试性

### ISSUE THREAD

**Issue by gengxiaoxiaoxin** [1Panel-dev/appstore#16]
### 请描述您的需求或者改进建议
建议：上架App之前需进行本地测试。

问题：
1. 目前本地源码运行[1Panel](https://github.com/1Panel-dev/1Panel)，应用商店模块无法进行测试（1panel开发缺少这部分的文档，此模块无法正常使用，更新应用列表会出现错误 ）。

### 请描述你建议的实现方案
需要进一步确认

**Comment by zhengkunwang223** [comment]
感谢建议 我们后续版本会支持

**Comment by zhengkunwang223** [comment]
v1.1 版本已经支持本次测试应用
https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8#5-%E6%9C%AC%E5%9C%B0%E6%B5%8B%E8%AF%95
