### ISSUE TITLE
halo博客更新版本失败问题

### ISSUE THREAD

**Issue by shy-share** [1Panel-dev/appstore#175]
2023年6月30日的时候，halo博客更新版本到2.7.0  按理来说utc零点时间应该要刷新1panel的应用商店的，但是应用商店更新当中并没有halo可以升级的提示  @zhengkunwang223 cc
> 1panel 版本已经是最新的了，也已经点击过更新所有应用列表了

**Comment by zhengkunwang223** [comment]
> 2023年6月30日的时候，halo博客更新版本到2.7.0  按理来说utc零点时间应该要刷新1panel的应用商店的，但是应用商店更新当中并没有halo可以升级的提示  @zhengkunwang223 cc
> 
> > 1panel 版本已经是最新的了，也已经点击过更新所有应用列表了

1.renovate 没有检测到 Halo 版本更新
2.renovate 更新之后需要merge pr到本项目 然后发布到应用商店


如果着急的话，可以编辑一下应用 docker-compose.yml 文件的 的halo 的镜像版本，然后保存，就可以升级

**Comment by shy-share** [comment]
> > 2023年6月30日的时候，halo博客更新版本到2.7.0  按理来说utc零点时间应该要刷新1panel的应用商店的，但是应用商店更新当中并没有halo可以升级的提示  @zhengkunwang223 cc
> > > 1panel 版本已经是最新的了，也已经点击过更新所有应用列表了
> 
> 1.renovate 没有检测到 Halo 版本更新 2.renovate 更新之后需要merge pr到本项目 然后发布到应用商店
> 
> 如果着急的话，可以编辑一下应用 docker-compose.yml 文件的 的halo 的镜像版本，然后保存，就可以升级

确实是没有检测到halo的版本更新，所以没有也没有merge了

**Comment by shy-share** [comment]
> > 2023年6月30日的时候，halo博客更新版本到2.7.0  按理来说utc零点时间应该要刷新1panel的应用商店的，但是应用商店更新当中并没有halo可以升级的提示  @zhengkunwang223 cc
> > > 1panel 版本已经是最新的了，也已经点击过更新所有应用列表了
> 
> 1.renovate 没有检测到 Halo 版本更新 2.renovate 更新之后需要merge pr到本项目 然后发布到应用商店
> 
> 如果着急的话，可以编辑一下应用 docker-compose.yml 文件的 的halo 的镜像版本，然后保存，就可以升级

更新这个docker-compose.yml 文件之后，是要点击什么那，应用上的重建吗？ 在更新当中还是看不到这个版本的，没办法直接点击升级按钮
