### ISSUE TITLE
请求添加：AFFINE 一个注重隐私、本地优先、开源、即用型的Notion&Miro替代品

### ISSUE THREAD

**Issue by toohandsome** [1Panel-dev/appstore#1952]
AFFINE 是 一个注重隐私、本地优先、开源、即用型的Notion&Miro替代品。

官网：https://affine.pro/
github: https://github.com/toeverything/AFFiNE
docker-compose: https://github.com/toeverything/AFFiNE/blob/stable/.github/deployment/self-host/compose.yaml
私有部署：
https://docs.affine.pro/docs/self-host-affine
https://docs.affine.pro/docs/self-host-affine/run-affine-with-custom-options

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦将需求统一反馈到 [1Panel issue](https://github.com/1Panel-dev/1Panel/issues)。
