### ISSUE TITLE
1Panel本地应用商店订阅助手（应用开发调试小帮手）

### ISSUE THREAD

**Issue by xxxily** [1Panel-dev/appstore#310]
搞了个1Panel本地应用商店订阅助手，可以订阅自己或第三方的1Panel应用，也可用于提升1Panel应用的开发调试过程，有需要的可以试用下，欢迎issues提建议或反馈，如果搞得好，看有没有机会合并到appstore给大家使用。

项目地址：https://github.com/xxxily/local-appstore-for-1Panel

## 特性

- 可一键更新同步1Panel官网的应用商店应用到本地环境
- 支持将任意第三方仓库的应用同步到1Panel的本地应用商店
- 支持github，gitlab，gitee等公开仓库、私有仓库
- 支持将多个分散的仓库应用同步到1Panel的本地应用商店
- 支持自定义拉取的分支、克隆深度、访问代理等，方便灵活
- 同步脚本源码完全开源，可自行修改、扩展，可放心使用

## 使用场景

- 1Panel官方应用商店的应用更新慢，想要快速更新到本地进行使用
- 1Panel官方应用有BUG，或者版本太低，想要自己修改后使用
- 1Panel官方应用商店没有自己想要的应用，想要自己添加应用
- 由于某些原因没法上架到1Panel官方应用商店，定制自己的专属应用
- 用于快速调试开发1Panel应用，方便本地开发调试
- 想要将多个分散的仓库应用同步到1Panel的本地应用商店

## 效果演示

将1Panel appstore里最近更的应用一键同步到本地应用商店

![read_cron_task_result](https://raw.githubusercontent.com/xxxily/local-appstore-for-1Panel/main/docs/img/read_cron_task_result.png)

**Comment by zhengkunwang223** [comment]
感谢提供

**Comment by okxlin** [comment]
## 应用源安利

[1Panel 应用商店的非官方应用适配库](https://github.com/okxlin/appstore)
[1Panel Store Unofficial App Adaptation Repository](https://github.com/okxlin/appstore)

**Comment by QYG2297248353** [comment]
## 应用源推荐
`GitHub`：[Docker 应用商店 - 1Panel 版本](https://github.com/QYG2297248353/appstore-1panel)
`Gitea`：[Docker 应用商店 - 1Panel 版本](https://git.lifebus.top/Ms-Studio/appstore-1panel)
`Gitea`：[Docker 应用商店 - 1Panel 版本](https://gitea.com/QYG2297248353/appstore-1panel)
`Gitee`：[Docker 应用商店 - 1Panel 版本](https://gitee.com/qyg2297248353/appstore-1panel)
