### ISSUE TITLE
添加 clash for linux

### ISSUE THREAD

**Issue by Avey777** [1Panel-dev/appstore#84]
https://www.jb51.cc/linux/3807935.html
https://www.chenhaifei.com/?p=2005

**Comment by zhengkunwang223** [comment]
clash 不在考虑中

**Comment by Avey777** [comment]
> clash 不在考虑中

Why ? 这个工具支持docker呀！  很好用的

**Comment by zhengkunwang223** [comment]
> > clash 不在考虑中
> 
> Why ? 这个工具支持docker呀！ 很好用的

代理工具可能带来意想不到的麻烦
