### ISSUE TITLE
请问下该仓库可否内网离线安装

### ISSUE THREAD

**Issue by H-TWINKLE** [1Panel-dev/appstore#857]
请问下该仓库可否内网离线安装

**Comment by wanghe-fit2cloud** [comment]
> 请问下该仓库可否内网离线安装

安装包中，默认的应用镜像均来源于外网仓库，如果要内网使用，需要解决镜像来源问题。
> 可以将应用镜像手动 load 到本地或者在手动修改 compose 文件将镜像指向本地仓库。
