### ISSUE TITLE
更新vaultwarden 后 compose 文件的 environment 参数丢失

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/appstore#902]
更新vaultwarden 后 compose 文件的 environment 参数丢失
不知道是vaultwarden还是1panel更新导致的 都是昨天下午更新的

**Comment by wanghe-fit2cloud** [comment]
麻烦将问题反馈至 1Panel 主项目，该问题将会得到及时的反馈。
https://github.com/1Panel-dev/appstore/issues/443
