### ISSUE TITLE
创建应用时如何将配置文件导入安装地址

### ISSUE THREAD

**Issue by vybfi** [1Panel-dev/appstore#926]
开发者你好!
我在适配一个obsidian同步的应用到应用商店
但是其启动过程需要一个配置文件(local.ini)
请问我应该将配置文件放在应用目录的哪个位置呢?
![image](https://github.com/1Panel-dev/appstore/assets/52736701/e38004ed-cb02-4782-a6b3-cd368af74398)
还是说我应该写一个脚本将其拷贝到安装后的目录呢?
如果我需要写脚本, 请问脚本的运行目录在哪个位置, 我应该如何定位当前1panel的应用安装目录呢?

谢谢!

**Comment by vybfi** [comment]
@zhengkunwang223

**Comment by zhengkunwang223** [comment]
根据官方的 docker-compose 配置文件 或者 docker run 启动命令来写 一般在 docker-compose 文件的 volume 中 docker run 命令的 -v  中可以找到 或者你可以参考 appstore 项目中的其他应用配置

**Comment by vybfi** [comment]
好的, 谢谢, 我已经在1panel的issus中收到了另一位开发者的回复. 已经了解了相关事项
